#!/usr/bin/env sh
if [ -s "/home/darealcaffeine/.rvm/environments/ruby-1.9.2-p0" ] ; then
  \. "/home/darealcaffeine/.rvm/environments/ruby-1.9.2-p0"
  exec erb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/darealcaffeine/.rvm/environments/ruby-1.9.2-p0'"
  exit 1
fi
