#!/usr/bin/env sh
if [ -s "/home/darealcaffeine/.rvm/environments/system" ] ; then
  \. "/home/darealcaffeine/.rvm/environments/system"
  exec erb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/darealcaffeine/.rvm/environments/system'"
  exit 1
fi
