# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.migration.version", 5);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.startup.homepage_override.buildID", "20110419185614");
user_pref("browser.startup.homepage_override.mstone", "rv:2.0");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 3);
user_pref("extensions.enabledAddons", "langpack-en-GB@firefox.mozilla.org:4.0,langpack-en-US@firefox.mozilla.org:4.0,globalmenu@ubuntu.com:1.0.2,langpack-en-ZA@firefox.mozilla.org:4.0,ubufox@ubuntu.com:0.9,{972ce4c6-7e08-4474-a285-3208198ce6fd}:4.0");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1303772427000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-4.0/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1303756311000},\"langpack-en-US@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-4.0/extensions/langpack-en-US@firefox.mozilla.org.xpi\",\"mtime\":1303756311000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox-4.0/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1303772210000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox-4.0/extensions/globalmenu@ubuntu.com\",\"mtime\":1303772211000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-4.0/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1303756311000}}}]");
user_pref("extensions.lastAppVersion", "4.0");
user_pref("extensions.pendingOperations", false);
user_pref("places.history.expiration.transient_current_max_pages", 10298);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
