#!/usr/bin/env sh
if [ -s "/home/darealcaffeine/.rvm/environments/ruby-1.8.7-p302" ] ; then
  \. "/home/darealcaffeine/.rvm/environments/ruby-1.8.7-p302"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/darealcaffeine/.rvm/environments/ruby-1.8.7-p302'"
  exit 1
fi
